apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-api
  namespace: httpbin
  labels:
    app: httpbin
spec:
  name: httpbin
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.httpbin.svc
    listen_path: /httpbin
    strip_listen_path: true