version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: brianoh1979/macos-runner
    steps:
      - checkout
      - run: kubectl create configmap oas-api-config-test22 --from-file=./oas/oas-api-definition-test21.json -n tyk --dry-run=client -o yaml | kubectl replace -f -
      - run: kubectl get tykoasapidefinition brian-test22 
