apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: not-important
spec:
  tags:
    - staging
  detailed_tracing: true
  CORS:
    enable: true
    allowed_origins:
    - "*"
    allowed_methods:
    - GET
    - POST
    - OPTIONS
    allowed_headers:
    - Authorization
    - Content-Type
    exposed_headers:
    - X-Custom-Header
    allow_credentials: true
